name: cp
dependencies:
  - python>3.4
  - pip
  - numpy
  - numba>=0.43.1
  - pyqt
  - scipy
  - pip:
    - mxnet-mkl
    - opencv-python-headless
    - pyqtgraph==0.11.0rc0
    - natsort
    - google-cloud-storage
    - tqdm
    - tifffile
    - cellpose
